static const AVInputFormat * const demuxer_list[] = {
    &ff_aac_demuxer,
    &ff_asf_demuxer,
    &ff_avi_demuxer,
    &ff_concat_demuxer,
    &ff_data_demuxer,
    &ff_flac_demuxer,
    &ff_flv_demuxer,
    &ff_live_flv_demuxer,
    &ff_hevc_demuxer,
    &ff_hls_demuxer,
    &ff_matroska_demuxer,
    &ff_mjpeg_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_mpegps_demuxer,
    &ff_mpegts_demuxer,
    &ff_mpegvideo_demuxer,
    &ff_rm_demuxer,
    &ff_rtsp_demuxer,
    &ff_webm_dash_manifest_demuxer,
    NULL };
