static const AVCodec * const codec_list[] = {
    &ff_png_encoder,
    &ff_flv_decoder,
    &ff_h263_decoder,
    &ff_h263i_decoder,
    &ff_h263p_decoder,
    &ff_h264_decoder,
    &ff_hevc_decoder,
    &ff_mjpeg_decoder,
    &ff_mpeg4_decoder,
    &ff_vp6_decoder,
    &ff_vp6f_decoder,
    &ff_vp8_decoder,
    &ff_vp9_decoder,
    &ff_aac_decoder,
    &ff_aac_latm_decoder,
    &ff_flac_decoder,
    &ff_mp3float_decoder,
    &ff_mp3_decoder,
    &ff_mp3adufloat_decoder,
    &ff_mp3adu_decoder,
    &ff_mp3on4float_decoder,
    &ff_mp3on4_decoder,
    NULL };
